general {
    hide_cursor = true
}

background {
    monitor =
    color = rgba(232136ff)
    blur_passes = 2
    blur_size = 7
}

label {
    monitor =
    text = $TIME
    font_size = 64
    color = rgba(e0def4ff)
    position = 0, 120
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2

    outer_color = rgba(c4a7e7ff)
    inner_color = rgba(2a273fff)
    font_color = rgba(e0def4ff)

    placeholder_text = Password...
    fail_text = $FAIL

    position = 0, -20
    halign = center
    valign = center
}
